projectdata <- read.table("household_power_consumption.txt", header = T,sep = ';',na.strings = "?")
pl4data <- subset(projectdata, Date %in% c("1/2/2007", "2/2/2007"))
pl4data$Date <- as.Date(pl4data$Date, format="%d/%m/%Y")
datetime <- paste(as.Date(pl4data$Date), pl4data$Time)
pl4data$Datetime <- as.POSIXct(datetime)
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(pl4data, {plot(Global_active_power~Datetime, type="l", xlab="", ylab="Global Active Power")
  plot(Voltage~Datetime, type="l", xlab="datetime", ylab="Voltage")
  plot(Sub_metering_1~Datetime, type="l", xlab="", ylab="Energy sub metering")
  lines(Sub_metering_2~Datetime, col="Red")
  lines(Sub_metering_3~Datetime, col="Blue")
  legend("topright", col=c("black", "red", "blue"),lty=1, lwd=1, bty="n", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(Global_reactive_power~Datetime, type="l", xlab="datetime", ylab="Gloabl_reactive_power")
})
dev.copy(png, file="plot4.png", height=480, width=480)
dev.off()