projectdata <- read.table("household_power_consumption.txt", header = T,sep = ';',na.strings = "?")
pl1data <-subset(projectdata, Date %in% c("1/2/2007","2/2/2007"))
pl1data$Date <- as.Date(pl1data$Date, format="%d/%m/%Y")
hist(pl1data$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", ylab = "Frequency", col = "Red")
dev.copy(png, file="plot1.png", height=480, width=480)
dev.off()