projectdata <- read.table("household_power_consumption.txt", header = T,sep = ';',na.strings = "?")
pl3data <- subset(projectdata, Date %in% c("1/2/2007", "2/2/2007"))
pl3data$Date <- as.Date(pl3data$Date, format="%d/%m/%Y")
datetime <- paste(as.Date(pl3data$Date), pl3data$Time)
pl3data$Datetime <- as.POSIXct(datetime)
with(pl3data, {plot(Sub_metering_1~Datetime, type="l", xlab = "", ylab = "Energy sub metering")
  lines(Sub_metering_2~Datetime, col="Red")
  lines(Sub_metering_3~Datetime, col="Blue")
  })
legend("topright", col = c("black","red","blue"), lty=1, lwd=1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png", height=480, width=480)
dev.off()